### ISSUE TITLE
Could not load completion data: 'gbk' codec can't decode byte 0x99 in positon..

### ISSUE THREAD

**Issue by ShuguangSun** [gaalcaras/ncm-R#8] opened 2018-01-28 08:32 UTC
System: Windows in Chinese (gbk/cp936)
Vim: Vim 8
Python: 3.6.3 (will it be supposed to utf8 as default?)

Nvim-R and ncm-R are used. When I type in the R script files, it raise the error message:
Could not load completion data: 'gbk' codec can't decode byte 0x99 in positon..
It has been set:

  set fileencodings=utf-8,cp936,big5,euc-jp,euc-kr,latin1,ucs-bom

In .Rprofile : options(encoding = "UTF-8")
I don't know why the gbk codec comes.

**Comment by gaalcaras** [comment] 2018-01-28 11:22
Thanks for your feedback.

Someone else already reported this bug, but it seemed it didn't prevent completion from working. Do you just get the warning or is completion broken as well?

I'm working on a fix right now, I'll updated you when I release it.

**Comment by ShuguangSun** [comment] 2018-01-28 16:48
You are right. Some of the files in g:rplugin_compldir are not UTF-8.

**Comment by gaalcaras** [comment] 2018-01-30 13:54
All right. Can you please answer the following questions? That would be helpful to write a patch, I'd like to improve the way ncm-R loads completion data:

+ Does completion work or not (in spite of the error message)?
+ Which files are not UTF-8?

**Comment by ShuguangSun** [comment] 2018-01-30 15:22
It is from Nvim-R:
[https://github.com/jalvesaq/Nvim-R/issues/276#issuecomment-361588169](https://github.com/jalvesaq/Nvim-R/issues/276#issuecomment-361588169)

**Comment by gaalcaras** [comment] 2018-01-30 18:05
Okay, thank you! I see the problem is already solved in Nvim-R, so I'm closing this issue.

**Closed by gaalcaras** 2018-01-30 18:05 UTC

**Comment by ShuguangSun** [comment] 2018-01-31 06:58
Just for document.
In window, the function **open** will decide the encoding according to the system local (in my case gbk). Even if the file is encoded using utf-8, python open will try to decode it with gbk. It is the error message comes.

In python 3, "encoding='utf-8' in open function can help. However it has side effect and requires all omnils encoded using 'utf-8'. 
```python
open(pkg_desc, encoding='utf-8', mode = 'r')
```

**Comment by gaalcaras** [comment] 2018-01-31 08:41
Exactly, that's what https://github.com/gaalcaras/ncm-R/commit/ff3297b8b134847db5107e48c4b75f56ee89ec1e did 😉
